### ISSUE TITLE
Readme for how to use the ci system

### ISSUE THREAD

**Issue by helinwang** [wangkuiyi/ci#10]
Now I have to dig into code to understand how it works.
I am going to create a readme after finishing https://github.com/wangkuiyi/ci/issues/15 (this issue depends on it)

**Comment by wangkuiyi** [comment]
Completely agree. I am not sure if the code is implementing the idea described in https://github.com/wangkuiyi/ci/issues/8

**Comment by helinwang** [comment]
Will do this after https://github.com/wangkuiyi/ci/issues/15 (handle pull request), I think before pull request is handled, the ci is far from feature complete. Thus that issue have high priority than this one.

**Comment by helinwang** [comment]
@wangkuiyi I think it will be similar to https://github.com/wangkuiyi/ci/issues/8 after https://github.com/wangkuiyi/ci/issues/15 being implemented.
