### ISSUE TITLE
builder.go不应该把shell script template这样的细节暴露给用户吧

### ISSUE THREAD

**Issue by wangkuiyi** [wangkuiyi/ci#13]
因为builder.go有很多办法来实现build，生成一个shell script并不一定是最好的，可能将来会被修改成直接调用 `os.exec.Command` 来启动子进程，比如[这个方法](http://www.darrencoxall.com/golang/executing-commands-in-go/)。

在这样的情况下，最好不要把builder.go里的细节暴露给用户，允许用户选择bash script的template: https://github.com/wangkuiyi/ci/blob/develop/builder.go#L53

**Comment by helinwang** [comment]
@wangkuiyi 同意，准备重新定义一下`config.yaml`支持的选项（现在支持在里面定义bash template）。准备去掉允许用户自定义bash template。另外在考虑是不是把所有的选项改成强制的（现在code里有默认的值，`config.yaml`只负责覆盖。
我看了你给的例子link，现在确实已经用`os.exec.Command`了（现在写shell script到文件，然后通过`os.exec.Command`运行。）`os.exec.Command`应该只能运行文件系统里的script，或者$PATH里面的命令，无法直接运行in memory script内容。

**Comment by helinwang** [comment]
This is fixed in https://github.com/wangkuiyi/ci/pull/22
