### ISSUE TITLE
根据不同的操作系统，运行环境，可以设置环境变量

### ISSUE THREAD

**Issue by reyoung** [wangkuiyi/ci#5]
入口的脚本是根目录下的 ci.sh

**Comment by wangkuiyi** [comment]
支持多种 configurations 确实是很必要的。具体做法可能知得商榷，我写在 [这个comment](https://github.com/wangkuiyi/ci/pull/6#issuecomment-257073289)里了，拷贝过来如下：

---

如果
1. 在不同的机器上跑多个configurations，并且
2. 一台机器可能跑多个并行的configurations，比如一台Linux机器上可以跑 in docker 和 in vm tests，

那么我理解**最好每个 configuration 是一个以 configuration 命名的 bash 脚本**，而不是一个统一的 bash 脚本，以环境变量决定其中被执行的内容，因为
1. 其实由 ci 系统决定执行那个脚本即可，而不需要 ci 系统和 test bash script 一起决定（ci 设置环境变量，bash script 按照环境变量值执行）
2. 避免万一 bash script 没有覆盖所有可能的环境变量值的麻烦。

**Comment by helinwang** [comment]
现在就是按照益哥的comment这样设计的，具体实在 https://github.com/wangkuiyi/ci/pull/22 实现的。
