### ISSUE TITLE
简单的CI系统设计

### ISSUE THREAD

**Issue by reyoung** [wangkuiyi/ci#8]
# CI系统功能

This is a simplified design compared with https://github.com/wangkuiyi/ci/issues/7 that there is no master node and that each worker has its own Webhook.

这个CI系统可以支持:

* 用户自定义运行的流程，环境变量等等
* 支持运行在Windows，Mac，Linux等系统上，并且支持多个配置。
* 监听PullRequest和Push两个Event
   * Push是检查每一个版本库内部的版本，是不是能够通过CI。(检查出例如 merge error之类的bug)
   * PullRequest是检查每一个PR是否正确。(即用户提交的code是不是有bug)
       * PR可以被修改非常多次，所以一个Event应该可以对应多个Build
* 可以重启，取消 Build
* 可以实时查看正在进行的Build的日志和已经完成的Build日志。

## 系统设计
整体的系统设计如下图所示，其中中间的tunnel只是一个中继服务器，将github的请求直接转发给后台服务。所以，中继服务器其实也可以去掉，只是我们只想让一台服务器能够被外网访问。

![image](https://cloud.githubusercontent.com/assets/728699/19917792/40171bee-a101-11e6-9097-af4bf20d57dd.png)

对于每一个配置，我们都启动一个独立的CI Server。这样可以让实现更简单。这相当于github上每次PR会有很多Check，每一个Check表示一个配置。
![image](https://cloud.githubusercontent.com/assets/728699/19917379/be190ff6-a0fd-11e6-8da2-370649278ba9.png)

#### 主函数

```go
for event := range webhook {  // 对于每一个事件
switch event.(type) {
case *PushEvent:
    pe := event.(*PushEvent)
    buildId := InsertPushEventToDB(pe)  // 返回build table的id
    buildQueue <- buildId  // send build 的id到Queue
case *PREvent:
   ... // 基本上同上
}
}
```

#### Build routine
这里有几个基本的想法:

* 所有的命令全部生成一个shell文件，并且通过执行这个shell文件来执行命令。
* 这个shell文件的生成过程，使用golang的template，用户可以配置。但是默认给出一个简单的实现。

```go
for buildId := range buildQueue {
    // 根据配置文件和build id来生成ci的shell脚本。包括git clone等命令，全是这个shell脚本的工作。
    // 这个shell脚本的生成工作，使用template，代码在 https://github.com/wangkuiyi/ci/blob/refine_ci_server/src/ci/ci_server/builder.go
    // 而这个template可以在配置文件里面配置。
    cmd = CreateShellFileFromBuildId(buildId)
    stdoutChan, stderrChan := execute(cmd)
    for !exit {
        select stdout/stderr to output.
        save output to database.
    }
}
```

### 配置文件

样例: https://github.com/wangkuiyi/ci/blob/refine_ci_server/configs/ci.yaml

* 用户可以配置concurrent数量，即有多少个build routine
* 用户可以配置Env，这些环境变量在ci脚本执行之前export
* 用户可以完全自主配置所有shell脚本的模板，这样，可以有非常强的自定义性。
   * 目前的模板在 https://github.com/wangkuiyi/ci/blob/refine_ci_server/src/ci/ci_server/conf.go#L60
* 用户可以定义执行的文件名
   * 默认是项目目录下的./ci.sh

### 一些奇怪的使用方式

其实这个系统可以不只做CI，也可以做两个mirror间的同步工作。而且这个同步的shell脚本可以不写在版本库中。

比如，可以将配置文件设置成

```yaml
build:
  filename: ../sync_mirror.sh
```

然后在sync_mirror.sh中写如何同步两个版本库的工作。

**Comment by wangkuiyi** [comment]
我没有太看明白为什么要同时处理 Push 和 PullRequest 两个 events。我再去看看文档，增强理解。

**Comment by wangkuiyi** [comment]
我理解在架构图里，每个机器上都有独立的ngrok tunnel，而不是所有机器通过一个tunnel？

**Comment by wangkuiyi** [comment]
原文中没有定义“配置”就使用了这个词。为了说明更清楚，我加上了一段说明以及指向 https://github.com/wangkuiyi/ci/issues/7 的连接，在 https://github.com/wangkuiyi/ci/issues/7 有“配置”（configuration）的定义。

**Comment by reyoung** [comment]
> 我理解在架构图里，每个机器上都有独立的ngrok tunnel，而不是所有机器通过一个tunnel？
> 是的。
> 
> 我没有太看明白为什么要同时处理 Push 和 PullRequest 两个 events。我再去看看文档，增强理解。

我也不是特别确定是不是要同时处理这两个Event，不过，应该在PR阶段就对代码进行持续集成的测试了。

**Comment by helinwang** [comment]
我本来的理解是我们会禁止直接push到branch，只允许pull request（不然要是允许push，ci check感觉就有点晚了，代码已经入库了）。需要支持push吗？

**Comment by helinwang** [comment]
赞多个status check的提议！感觉在现阶段每个机器独立运行一个status很简单方便。

**Comment by reyoung** [comment]
> 我本来的理解是我们会禁止直接push到branch，只允许pull request（不然要是允许push，ci check感觉就有点晚了，代码已经入库了）。需要支持push吗？

需要因为，merge可能有conflict。就是即使git说没有conflict，merge进去了，但是单测也有可能挂。

比如 

``` python
stat = 0

def func1():
    stat = 1
```

``` python
def func2():
    stat = 2

stat = 0
```

这个一合就有问题了。虽然没有conflict

**Comment by wangkuiyi** [comment]
我记得我做过实验：git push 不管push到哪个branch，哪怕是push某个feature branch，都会触发PushEvent。

> PullRequest Event
> Triggered when a pull request is assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, or synchronized.

从这个解释看，PullRequestEvent是不需要处理的。和CI没有关系。

**Comment by helinwang** [comment]
@reyoung 明白了，push确实是必须的。谢谢指明。
@cxwangyi 如果只处理push，那么我理解正确的话，每次检查build是否通过就要等到代码merge到master。如果branching model是master的代码是可以break的，这样就没问题。
另外，我搜索了下，看有些人确实在request pull request (PR) 可以trigger build的功能 (e.g., https://discuss.circleci.com/t/pull-requests-not-triggering-build/1213/10)。
我想了下，有以下几点好处作为参考。我们并不一定需要implement这个功能。
好处有：
- PR的时候就知道merge进去之后会不会break build （前提是每个别的commit进入master都需要rebuild申请merge到master的所有PR)
- PR的时候就知道test coverage，能够对比test coverage前后的差别。

有了这两点，对代码入库的管理更严格。

**Comment by reyoung** [comment]
#6 基本上把主体的code搞定了，除了http的显示界面。目前只处理了PushEvent，不过可以扩展成支持PR。

具体的http界面和目前的使用，我在今天在写一个文档说明一下。

**Comment by wangkuiyi** [comment]
@helinwang @reyoung 目前我们的README.md是空的。目前源码里实现的是这里讨论的思路吗？应该有一个PR更新到README.md里？

**Comment by wangkuiyi** [comment]
哦。我看到鹤麟有计划 https://github.com/wangkuiyi/ci/issues/10 了。关掉这个issue了。
